### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/scrollreveal#1]
@biolithic I see you are seeking maintainers -- do you mind if I take this one over?

**Comment by laryn** [comment]
@biolithic Flagging one more time. Do you mind if I assume maintainership on this one?

**Comment by quicksketch** [comment]
Hi @laryn, given the lack of response and the clear request for maintainers from the README, I've committed the change to the maintainers list at https://github.com/backdrop-contrib/scrollreveal/commit/8f441e690d51c3317c88b89cb38f1d74b7765b99.

We haven't done this very often so far, but I want to thank @biolithic for his port. If at all needed or desired, of course you may still commit/modify the module. Please update the maintainers list if needed.

**Comment by laryn** [comment]
Thanks, @quicksketch! I've got some improvements I'm working on and will release them later this week. And thanks @biolithic for the port.
