### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/scrollreveal#12]
I just tried installing this through the UI and got a fatal error. This is in the watchdog:

> `ConfigStorageReadException: The configuration file "scrollreveal.settings" is not properly formatted JSON. Contents: <pre>{ &quot;_config_name&quot;: &quot;scrollreveal.settings&quot;, &quot;config&quot;: { &quot;origin&quot;: &quot;top&quot;, &quot;distance&quot;: 24, &quot;duration&quot;: 500, &quot;delay&quot;: 0, &quot;interval&quot;: 0, &quot;rotate_x&quot;: 0, &quot;rotate_y&quot;: 0, &quot;rotate_z&quot;: 0, &quot;opacity&quot;: 0, &quot;scale&quot;: 0.9, &quot;easing&quot;: &quot;ease&quot;, &quot;mobile&quot;: &quot;true&quot;, &quot;reset&quot;: &quot;false&quot;, &quot;useDelay&quot;: &quot;always&quot;, &quot;viewportFactor&quot;: 0.2, }, &quot;pages&quot;: { &quot;visibility&quot;: 0, &quot;pages&quot;: &quot;admin/*&quot; }, &quot;theme&quot;: { &quot;visibility&quot;: 1 } } </pre> in ConfigFileStorage->read() (line 1134 of /path/core/includes/config.inc).`

**Comment by laryn** [comment]
Also:

> Notice: Undefined index: pages in scrollreveal_init() (line 46 of /path/modules/scrollreveal/scrollreveal.module).

> Notice: Undefined index: theme in scrollreveal_init() (line 47 of /path/modules/scrollreveal/scrollreveal.module).

> Warning: in_array() expects parameter 2 to be array, null given in scrollreveal_check_theme() (line 114 of /path/modules/scrollreveal/scrollreveal.module).

**Comment by laryn** [comment]
@BWPanda I deleted and installed 1.x-2.0 (instead of the latest release) and it installed fine. Then I upgraded and it also went fine. 

Can you double check the changes you made in 1.x-2.0.1? Do you get these errors if installing on a fresh site?

**Comment by ghost** [comment]
@laryn Yep, got the same issues when installing the latest version. Problem was an extra comma in the config file (:roll_eyes:) and then also discovered an issue with an option being named incorrectly.

Are you able to confirm my committed changes fix everything for you before I roll a new release?

**Comment by laryn** [comment]
@BWPanda Confirmed, looks good!

**Comment by ghost** [comment]
Great, thanks! New release available: https://github.com/backdrop-contrib/scrollreveal/releases/tag/1.x-2.0.2
