### ISSUE TITLE
`Reset effect: false` doesn't work

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/scrollreveal#4]
Even though I have 'Reset effect' set to FALSE, all my animations are replayed each time I scroll to them.

**Comment by laryn** [comment]
I'm not seeing this, can you provide more info, @BWPanda? I just installed fresh and set up a simple animation for the footer. When I scroll down, it animates. Then I scroll up and down again and there is no animation.

**Comment by ghost** [comment]
I did the same as you - fresh install, setup animation on footer block with default settings (making sure Reset was False), and the issue happens for me. See here:

![peek 2018-07-30 21-05](https://user-images.githubusercontent.com/2385329/43414880-b98ca900-943c-11e8-8200-ea35ecb594b2.gif)

**Comment by laryn** [comment]
I'll have to dig a little deeper on this. Thanks for the detailed follow up!

**Comment by laryn** [comment]
After testing with the correct version (I used the Project Installer the first time and it installed the old version for some reason...) I'm a bit stumped on this one. It looks like the value is set correctly but just not working correctly. Any ideas, @BWPanda?

**Comment by ghost** [comment]
I'll have a look when I re-write the module for you :wink: (https://github.com/backdrop-contrib/scrollreveal/issues/5#issuecomment-409318875)

**Comment by ghost** [comment]
Ok, turns out the TRUE/FALSE values set by the module were strings, and they equate to TRUE all the time (`'false' == TRUE` in javascript). So I fixed that with [this commit](https://github.com/backdrop-contrib/scrollreveal/commit/ead08e14731721fa01b3df43ca456f674702b874) as part of https://github.com/backdrop-contrib/scrollreveal/issues/8.
