### ISSUE TITLE
Easier use of defaults

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/scrollreveal#5]
I think an easier way to set/use default values would be to allow leaving element values blank, and then using default values for any blank ones.

For example, you setup your default values in the Default Settings fieldset. Then you create different elements below. All values should be blank (which means they'll use the defaults above), but you can set them manually otherwise.

This basically solves the problem of looking through an element's values and trying to work out what has been customised from the default. It also means changing the default values after creating a few elements means they'll automatically inherit those values, rather than you needing to change them back to the defaults manually.

**Comment by laryn** [comment]
Good idea! If you get a chance to roll a PR I'll include it. I'm not sure when I'd be able to get to it.

**Comment by ghost** [comment]
Done! See attached PR.

I think it's working from my testing, but please feel free to go over it yourself to make sure everything still works as expected.

I re-jigged the install file as it was storing default values unnecessarily (moved them to the config file instead, except the theme setting which remains in `hook_install()`.
There's a lot more that can be cleaned up/made standards-compliant, but I forced myself to resist fixing everything and just focus on this issue :wink:

**Comment by laryn** [comment]
Great, thanks! It looks good by eye so I'm going to merge and work from this while troubleshooting the other issue.

> There's a lot more that can be cleaned up/made standards-compliant, but I forced myself to resist fixing everything and just focus on this issue 😉

Please, feel free! 😄 The project I will need this for is still a few months away so I ported and tried to update in anticipation but am aware it could still use some spit-and-polish. If you're keen to be a co-maintainer, I'm open to that, too!
