### ISSUE TITLE
Standardise and cleanup code

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/scrollreveal#8]
As per https://github.com/backdrop-contrib/scrollreveal/issues/5#issuecomment-409318875 I'm going to make some changes to the code to clean it up and standardise it a bit :grin:

**Comment by laryn** [comment]
@BWPanda++

**Comment by ghost** [comment]
PR attached!

**Comment by laryn** [comment]
Awesome! I'll try to look at it tomorrow. 
Are you interested in being a co-maintainer, or prefer not?

**Comment by ghost** [comment]
Sure

**Comment by laryn** [comment]
@BWPanda FTW
